// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzsDrrIDH6FLRFkrUDBOUzCp1-u8mP0iM',
    appId: '1:270493720321:web:31e589c422cc9cf0a3c500',
    messagingSenderId: '270493720321',
    projectId: 'chat-app-3d186',
    authDomain: 'chat-app-3d186.firebaseapp.com',
    storageBucket: 'chat-app-3d186.appspot.com',
    measurementId: 'G-JN28HDRREV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClUENq1iTmv1KX8hhgPHlIhyQUhbzabNk',
    appId: '1:270493720321:android:65999400f9043214a3c500',
    messagingSenderId: '270493720321',
    projectId: 'chat-app-3d186',
    storageBucket: 'chat-app-3d186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-xyQ8z16CPxm_ImbXCpvfUageZWnOQIo',
    appId: '1:270493720321:ios:7b4e5c46b9ea0fafa3c500',
    messagingSenderId: '270493720321',
    projectId: 'chat-app-3d186',
    storageBucket: 'chat-app-3d186.appspot.com',
    iosClientId: '270493720321-a7ibqq5h5mhkn911834qlifqt07v50rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-xyQ8z16CPxm_ImbXCpvfUageZWnOQIo',
    appId: '1:270493720321:ios:7b4e5c46b9ea0fafa3c500',
    messagingSenderId: '270493720321',
    projectId: 'chat-app-3d186',
    storageBucket: 'chat-app-3d186.appspot.com',
    iosClientId: '270493720321-a7ibqq5h5mhkn911834qlifqt07v50rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
